# https://github.com/marketplace/actions/publish-docker
name: Deploy
on: [push]
jobs:
  build:
    name: dockerhub
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: git archive -o docker/amici.tar.gz --format=tar.gz HEAD
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: dweindl/amici
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: docker/
        dockerfile: Dockerfile
        tag_names: true
