name: SBML semantic test suite
on:
  push:
    paths:
      - python/amici/sbml_import.py
      - python/amici/ode_export.py
  pull_request:
    branches:
      - master
    paths:
      - python/amici/sbml_import.py
      - python/amici/ode_export.py

jobs:
  build:
    name: SBML semantic test suite

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: apt
      run: |
        sudo apt-get update \
          && sudo apt-get install -y swig3.0 libatlas-base-dev \
          && sudo ln -s /usr/bin/swig3.0 /usr/bin/swig
    - run: AMICI_PARALLEL_COMPILE=2 ./scripts/installAmiciSource.sh
    - run: AMICI_PARALLEL_COMPILE=2 ./scripts/run-SBMLTestsuite.sh
