name: Matlab
on: [push, pull_request, workflow_dispatch]

jobs:
  matlab:
    name: Matlab

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - run: git fetch --prune --unshallow

    - run: echo "AMICI_DIR=$(pwd)" >> $GITHUB_ENV

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v0
    - name: Run script
      uses: matlab-actions/run-command@v0
      with:
        command: cd matlab; installAMICI
