name: Conda installation
on:
  workflow_dispatch:
  schedule:
    - cron: '48 4 * * *'
  pull_request:
    branches:
      - main

jobs:
  conda:
    name: Conda installation
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          activate-environment: amici
      - name: Install requirements
        shell: bash -l {0}
        run: |
          conda install -c conda-forge compilers cmake
      - name: Install AMICI
        shell: bash -l {0}
        run: |
          pip3 install -v ./python/sdist
      - name: Show environment
        shell: bash -l {0}
        run: |
          python -c "import os; import pprint; pprint.pprint(dict(os.environ))"
          which cmake
          which ninja
          ls -l /Users/runner/miniconda3/envs/amici/bin || true
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          # Install test extras (pytest, scipy, etc.)
          pip3 install pytest pytest-cov scipy h5py antimony
      - name: Test import
        shell: bash -l {0}
        run: |
          python -c "from amici._installation import _amici; print(_amici)"
          python -m amici
      - name: Run SBML import test
        shell: bash -l {0}
        # FIXME
        continue-on-error: true
        run: |
          cd python/tests
          pytest test_sbml_import.py::test_steadystate_simulation -sv
